# Credit to https://github.com/Mikyuwu/Cutie-dots/blob/NEW-Cutie-dots/config/matugen/templates/spicetify-colors.ini

[Matugen]
text               = e5e1e9
subtext            = c9c5d0
main               = 141318
main-elevated      = 141318
main-transition    = 141318
highlight          = 3a383e
highlight-elevated = 3a383e
sidebar            = 201f25
player             = 201f25
card               = 201f25
shadow             = c7bfff
selected-row       = c7bfff
button             = c7bfff
button-active      = c7bfff
button-disabled    = c7bfff
tab-active         = 3a383e
notification       = 201f25
notification-error = c7bfff
misc               = c7bfff
play-button        = e5deff
play-button-active = c7bfff
progress-fg        = c7bfff
progress-bg        = 3a383e
heart              = c7bfff
pagelink-active    = c7bfff
radio-btn-active   = c7bfff
