
$image = /home/zorvi/Pictures/wp/lmkgqp.png
$background = rgba(181215ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$error = rgba(ffb4abff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$error_container = rgba(93000aff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$inverse_on_surface = rgba(362e32ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$inverse_primary = rgba(844c73ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$inverse_surface = rgba(ecdfe4ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_background = rgba(ecdfe4ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_error = rgba(690005ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_error_container = rgba(ffdad6ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_primary = rgba(4f1e43ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_primary_container = rgba(ffd7efff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_primary_fixed = rgba(36072dff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_primary_fixed_variant = rgba(69345bff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_secondary = rgba(3f2a38ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_secondary_container = rgba(fadaecff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_secondary_fixed = rgba(281622ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_secondary_fixed_variant = rgba(56404eff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_surface = rgba(ecdfe4ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_surface_variant = rgba(d2c2caff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_tertiary = rgba(4b2716ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_tertiary_container = rgba(ffdbcdff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_tertiary_fixed = rgba(321205ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$on_tertiary_fixed_variant = rgba(663c2aff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$outline = rgba(9b8d94ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$outline_variant = rgba(4f444aff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$primary = rgba(f6b2dfff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$primary_container = rgba(69345bff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$primary_fixed = rgba(ffd7efff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$primary_fixed_dim = rgba(f6b2dfff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$scrim = rgba(000000ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$secondary = rgba(ddbed0ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$secondary_container = rgba(56404eff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$secondary_fixed = rgba(fadaecff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$secondary_fixed_dim = rgba(ddbed0ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$shadow = rgba(000000ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$source_color = rgba(42323cff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface = rgba(181215ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_bright = rgba(3f373bff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_container = rgba(251e22ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_container_high = rgba(2f282cff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_container_highest = rgba(3a3337ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_container_low = rgba(201a1eff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_container_lowest = rgba(120c10ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_dim = rgba(181215ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_tint = rgba(f6b2dfff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$surface_variant = rgba(4f444aff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$tertiary = rgba(f5b9a1ff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$tertiary_container = rgba(663c2aff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$tertiary_fixed = rgba(ffdbcdff)

$image = /home/zorvi/Pictures/wp/lmkgqp.png
$tertiary_fixed_dim = rgba(f5b9a1ff)

