#!/bin/zsh

read "P?path to config dir > "
read "T?container tag > "
read "N?container name > "
if [[ -z $P || -z $T || -z $N ]]; then
	echo "error:\npath: $P\ntag: $T\nname: $N"
	exit 1
fi

podman build --secret id=github_token,src=$HOME/dev/.github_token -t $T $P
podman run -d --name $N --hostname $N --net=host -v $HOME/dev/projects:/root/projects $T
#  $HOME/dev/projects:/root/projects 
