FROM archlinux:latest

# ISNTALL
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm base-devel openssh git sudo zsh mise nvim

# ZSH
RUN chsh -s /usr/bin/zsh && \
    cat <<'EOF' > /root/.zshrc
# base
HISTFILE=~/.histfile
SAVEHIST=1000
bindkey -e
PROMPT=' (%m) %F{cyan}%~%f %F{magenta}→%f '
# mise
eval "$(mise activate zsh)"
# auto complete
autoload -Uz compinit && compinit
EOF


# GIT
RUN cat <<EOF > /root/.gitconfig
[credential]
	helper = store
EOF
RUN --mount=type=secret,id=github_token \
    echo "https://aervxa:$(cat /run/secrets/github_token)@github.com" > /root/.git-credentials

#SSH
COPY containers.pub /root/.ssh/authorized_keys
RUN ssh-keygen -A
#CMD ["/usr/sbin/sshd", "-D", "-p", "2222", "-e", "-o", "PermitRootLogin=yes"]
CMD ["/usr/sbin/sshd", "-D", "-p", "2222", "-e"]
